package commands

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/spf13/cobra"
)

// initCmd runs the init wizard and sends config to server
var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Run configuration wizard (sends to server)",
	Run: func(cmd *cobra.Command, args []string) {
		reader := bufio.NewReader(os.Stdin)

		fmt.Println("=== Asika Configuration Wizard ===")
		fmt.Println()

		// Server config
		fmt.Print("Server listen address [':8080']: ")
		listen, _ := reader.ReadString('\n')
		listen = strings.TrimSpace(listen)
		if listen == "" {
			listen = ":8080"
		}

		fmt.Print("Server mode (debug/release) ['release']: ")
		mode, _ := reader.ReadString('\n')
		mode = strings.TrimSpace(mode)
		if mode == "" {
			mode = "release"
		}

		// Database
		fmt.Print("Database path ['/var/lib/asika/asika.db']: ")
		dbPath, _ := reader.ReadString('\n')
		dbPath = strings.TrimSpace(dbPath)
		if dbPath == "" {
			dbPath = "/var/lib/asika/asika.db"
		}

		// Auth
		fmt.Print("JWT secret (leave empty to generate): ")
		jwtSecret, _ := reader.ReadString('\n')
		jwtSecret = strings.TrimSpace(jwtSecret)

		fmt.Print("Token expiry ['72h']: ")
		tokenExpiry, _ := reader.ReadString('\n')
		tokenExpiry = strings.TrimSpace(tokenExpiry)
		if tokenExpiry == "" {
			tokenExpiry = "72h"
		}

		// Mode
		fmt.Print("Mode (single/multi) ['multi']: ")
		repoMode, _ := reader.ReadString('\n')
		repoMode = strings.TrimSpace(repoMode)
		if repoMode == "" {
			repoMode = "multi"
		}

		// Generate config
		configTOML := generateConfigForInit(listen, mode, dbPath, jwtSecret, tokenExpiry, repoMode)

		// Send to server via HTTP
		server, _ := cmd.Flags().GetString("server")
		if server == "" {
			server = "http://localhost:8080"
		}

		token, _ := cmd.Flags().GetString("token")
		if token == "" {
			token = os.Getenv("ASIKA_TOKEN")
		}

		// Convert TOML to JSON for API
		var cfg map[string]interface{}
		if err := toml.Unmarshal([]byte(configTOML), &cfg); err != nil {
			fmt.Printf("Error parsing config: %v\n", err)
			return
		}

		jsonData, err := json.Marshal(cfg)
		if err != nil {
			fmt.Printf("Error converting config: %v\n", err)
			return
		}

		url := fmt.Sprintf("%s/api/v1/config", server)
		req, err := http.NewRequest("PUT", url, bytes.NewBuffer(jsonData))
		if err != nil {
			fmt.Printf("Error: %v\n", err)
			return
		}
		req.Header.Set("Content-Type", "application/json")
		if token != "" {
			req.Header.Set("Authorization", "Bearer "+token)
		}

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			fmt.Printf("Error sending config to server: %v\n", err)
			return
		}
		defer resp.Body.Close()

		if resp.StatusCode != http.StatusOK {
			fmt.Printf("Server returned error: HTTP %d\n", resp.StatusCode)
			return
		}

		fmt.Println("Configuration sent to server successfully!")
		fmt.Println("The server will write the config file and reload.")
	},
}

func generateConfigForInit(listen, serverMode, dbPath, jwtSecret, tokenExpiry, repoMode string) string {
	if jwtSecret == "" {
		jwtSecret = "change-me-in-init"
	}

	return fmt.Sprintf(`# Asika Configuration
# Generated by asika init

[server]
listen = "%s"
mode   = "%s"

[database]
path = "%s"

[auth]
jwt_secret = "%s"
token_expiry = "%s"

[events]
mode = "webhook"

[git]
workdir = "/var/lib/asika/work"

[merge_queue]
required_approvals = 1

[spam]
enabled = true
time_window = "10m"
threshold = 3

[[repo_groups]]
name = "default"
mode = "%s"
`, listen, serverMode, dbPath, jwtSecret, tokenExpiry, repoMode)
}

func init() {
	RootCmd.AddCommand(initCmd)
}
