package commands

import (
	"bufio"
	"bytes"
	"encoding/json"
	"fmt"
	"net/http"
	"os"
	"strings"

	"github.com/BurntSushi/toml"
	"github.com/spf13/cobra"
)

// initCmd runs the init wizard and sends config to server
var initCmd = &cobra.Command{
	Use:   "init",
	Short: "Run configuration wizard (sends to server)",
	Run: func(cmd *cobra.Command, args []string) {
		reader := bufio.NewReader(os.Stdin)

		fmt.Println("=== Asika Configuration Wizard ===")
		fmt.Println()

		// Server config
		fmt.Print("Server listen address [':8080']: ")
		listen, _ := reader.ReadString('\n')
		listen = strings.TrimSpace(listen)
		if listen == "" {
			listen = ":8080"
		}

		fmt.Print("Server mode (debug/release) ['release']: ")
		mode, _ := reader.ReadString('\n')
		mode = strings.TrimSpace(mode)
		if mode == "" {
			mode = "release"
		}

		// Database
		fmt.Print("Database path ['/var/lib/asika/asika.db']: ")
		dbPath, _ := reader.ReadString('\n')
		dbPath = strings.TrimSpace(dbPath)
		if dbPath == "" {
			dbPath = "/var/lib/asika/asika.db"
		}

		// Auth
		fmt.Print("JWT secret (leave empty to generate): ")
		jwtSecret, _ := reader.ReadString('\n')
		jwtSecret = strings.TrimSpace(jwtSecret)

		fmt.Print("Token expiry ['72h']: ")
		tokenExpiry, _ := reader.ReadString('\n')
		tokenExpiry = strings.TrimSpace(tokenExpiry)
		if tokenExpiry == "" {
			tokenExpiry = "72h"
		}

		// Mode
		fmt.Print("Mode (single/multi) ['multi']: ")
		repoMode, _ := reader.ReadString('\n')
		repoMode = strings.TrimSpace(repoMode)
		if repoMode == "" {
			repoMode = "multi"
		}

		// Updates
		fmt.Print("Enable automatic update check? (y/n) ['n']: ")
		updateCheck, _ := reader.ReadString('\n')
		updateCheck = strings.TrimSpace(updateCheck)
		updateCheckEnabled := strings.ToLower(updateCheck) == "y" || strings.ToLower(updateCheck) == "yes"

		updateInterval := "24h"
		updateNotify := "n"
		if updateCheckEnabled {
			fmt.Print("Check interval ['24h']: ")
			ui, _ := reader.ReadString('\n')
			ui = strings.TrimSpace(ui)
			if ui != "" {
				updateInterval = ui
			}
			fmt.Print("Notify on new version? (y/n) ['n']: ")
			updateNotify, _ = reader.ReadString('\n')
			updateNotify = strings.TrimSpace(updateNotify)
		}

		updateCheckStr := "false"
		if updateCheckEnabled {
			updateCheckStr = "true"
		}
		updateNotifyStr := "false"
		if strings.ToLower(updateNotify) == "y" || strings.ToLower(updateNotify) == "yes" {
			updateNotifyStr = "true"
		}

		// Stale
		fmt.Print("Enable stale PR management? (y/n) ['n']: ")
		staleEnabled, _ := reader.ReadString('\n')
		staleEnabled = strings.TrimSpace(staleEnabled)
		staleEnabledBool := strings.ToLower(staleEnabled) == "y" || strings.ToLower(staleEnabled) == "yes"
		staleEnabledStr := "false"
		if staleEnabledBool {
			staleEnabledStr = "true"
		}

		staleInterval := "6h"
		if staleEnabledBool {
			fmt.Print("Check interval ['6h']: ")
			si, _ := reader.ReadString('\n')
			si = strings.TrimSpace(si)
			if si != "" {
				staleInterval = si
			}
		}

		// Generate config
		configTOML := generateConfigForInit(listen, mode, dbPath, jwtSecret, tokenExpiry, repoMode, updateCheckStr, updateInterval, updateNotifyStr, staleEnabledStr, staleInterval)

		// Send to server via HTTP
		server := GetServer(cmd)

		token := GetToken(cmd)

		// Convert TOML to JSON for API
		var cfg map[string]interface{}
		if err := toml.Unmarshal([]byte(configTOML), &cfg); err != nil {
			fmt.Printf("Error parsing config: %v\n", err)
			return
		}

		jsonData, err := json.Marshal(cfg)
		if err != nil {
			fmt.Printf("Error converting config: %v\n", err)
			return
		}

		url := fmt.Sprintf("%s/api/v1/config", server)
		req, err := http.NewRequest("PUT", url, bytes.NewBuffer(jsonData))
		if err != nil {
			fmt.Printf("Error: %v\n", err)
			return
		}
		req.Header.Set("Content-Type", "application/json")
		if token != "" {
			req.Header.Set("Authorization", "Bearer "+token)
		}

		resp, err := http.DefaultClient.Do(req)
		if err != nil {
			fmt.Printf("Error sending config to server: %v\n", err)
			return
		}
		defer resp.Body.Close()

		if resp.StatusCode != http.StatusOK {
			fmt.Printf("Server returned error: HTTP %d\n", resp.StatusCode)
			return
		}

		fmt.Println("Configuration sent to server successfully!")
		fmt.Println("The server will write the config file and reload.")
	},
}

func generateConfigForInit(listen, serverMode, dbPath, jwtSecret, tokenExpiry, repoMode, updateCheck, updateInterval, updateNotify, staleEnabled, staleInterval string) string {
	if jwtSecret == "" {
		jwtSecret = "change-me-in-init"
	}

	return fmt.Sprintf(`# Asika Configuration
# Generated by asika init

[server]
listen = "%s"
mode   = "%s"

[database]
path = "%s"

[auth]
jwt_secret = "%s"
token_expiry = "%s"

[events]
mode = "webhook"

[git]
workdir = "/var/lib/asika/work"

[merge_queue]
required_approvals = 1

[spam]
enabled = true
time_window = "10m"
threshold = 3

[updates]
check         = %s
interval      = "%s"
notify_on_new = %s

[stale]
enabled        = %s
check_interval = "%s"
days_until_stale = 21
days_until_close = 0
stale_label    = "stale"
exempt_labels  = ["long-term"]

[[repo_groups]]
name = "default"
mode = "%s"
`, listen, serverMode, dbPath, jwtSecret, tokenExpiry, updateCheck, updateInterval, updateNotify, staleEnabled, staleInterval, repoMode)
}

func init() {
	RootCmd.AddCommand(initCmd)
}
