package commands

import (
	"bufio"
	"fmt"
	"os"
	"strings"

	"github.com/spf13/cobra"
)

// wizardCmd runs the init wizard
var wizardCmd = &cobra.Command{
	Use:   "wizard",
	Short: "Run configuration wizard",
	Run: func(cmd *cobra.Command, args []string) {
		reader := bufio.NewReader(os.Stdin)

		fmt.Println("=== Asika Configuration Wizard ===")
		fmt.Println()

		// Server config
		fmt.Print("Server listen address [':8080']: ")
		listen, _ := reader.ReadString('\n')
		listen = strings.TrimSpace(listen)
		if listen == "" {
			listen = ":8080"
		}

		fmt.Print("Server mode (debug/release) ['release']: ")
		mode, _ := reader.ReadString('\n')
		mode = strings.TrimSpace(mode)
		if mode == "" {
			mode = "release"
		}

		// Database
		fmt.Print("Database path ['/var/lib/asika/asika.db']: ")
		dbPath, _ := reader.ReadString('\n')
		dbPath = strings.TrimSpace(dbPath)
		if dbPath == "" {
			dbPath = "/var/lib/asika/asika.db"
		}

		// Auth
		fmt.Print("JWT secret (leave empty to generate): ")
		jwtSecret, _ := reader.ReadString('\n')
		jwtSecret = strings.TrimSpace(jwtSecret)

		fmt.Print("Token expiry ['72h']: ")
		tokenExpiry, _ := reader.ReadString('\n')
		tokenExpiry = strings.TrimSpace(tokenExpiry)
		if tokenExpiry == "" {
			tokenExpiry = "72h"
		}

		// Mode
		fmt.Print("Mode (single/multi) ['multi']: ")
		repoMode, _ := reader.ReadString('\n')
		repoMode = strings.TrimSpace(repoMode)
		if repoMode == "" {
			repoMode = "multi"
		}

		// Generate config
		config := generateConfig(listen, mode, dbPath, jwtSecret, tokenExpiry, repoMode)

		// Write to file
		configPath := "/etc/asika_config.toml"
		fmt.Printf("Write config to %s? [Y/n]: ", configPath)
		confirm, _ := reader.ReadString('\n')
		confirm = strings.TrimSpace(strings.ToLower(confirm))
		if confirm == "" || confirm == "y" || confirm == "yes" {
			err := os.WriteFile(configPath, []byte(config), 0644)
			if err != nil {
				fmt.Printf("Error writing config: %v\n", err)
				return
			}
			fmt.Printf("Config written to %s\n", configPath)
		} else {
			fmt.Println("Config not written")
			fmt.Println("\nGenerated config:")
			fmt.Println(config)
		}
	},
}

func generateConfig(listen, mode, dbPath, jwtSecret, tokenExpiry, repoMode string) string {
	if jwtSecret == "" {
		jwtSecret = "change-me-in-wizard"
	}

	return fmt.Sprintf(`# Asika Configuration
# Generated by asika wizard

[server]
listen = "%s"
mode   = "%s"

[database]
path = "%s"

[auth]
jwt_secret = "%s"
token_expiry = "%s"

[events]
mode = "webhook"

[git]
workdir = "/var/lib/asika/work"

[merge_queue]
required_approvals = 1

[spam]
enabled = true
time_window = "10m"
threshold = 3

mode = "%s"
`, listen, mode, dbPath, jwtSecret, tokenExpiry, repoMode)
}
